baseURL = "https://jun-robot.netlify.app/"
title = "Junのロボット日記"
languageCode = "ja"
theme = "robust"



hasCJKLanguage = true # 省略を適切な長さに。

pygmentsCodefences = true # シンタックスハイライト ここ参考↓
pygmentsUseClasses = true # https://tech-babysteps.net/hugo-syntax-highlighting/

googleAnalytics = "G-D0TKMHP045" # Optional

[params]
    dateformat = "2006-01-02"
    copyrightYear = "2022 Jun-robot　"
    description = "ロボット好き高校生の開発記録"

    # twitterID = "@jun_robot"
    # description = "個人ブログです！"
    # images = ["/images/default.jpg"]
    
    # description = "Text about my cool site"
    # images = ["default.jpg"]
    # title = "My cool site"



[params.posts]
    show_thumb_post = true # 記事冒頭にサムネイルを表示させるか
    toc = false # 目次作成

[params.author]
    thumbnail = "/images/author.jpg"
    name = "<a href ='/pages/profile'>Jun</a>"
    description = "<p>千葉県に住んでいる高校生ロボカッパー。<br>ハードからソフトまで広く浅くやってます。</p>"
    facebook = "https://www.facebook.com/profile.php?id=100027609278755"
    twitter = "https://twitter.com/jun_robot"
    github = "https://github.com/Jun-robot"
    instagram = "https://www.instagram.com/jun.rcj/?hl=ja"
    mail = "https://forms.gle/zz9gU4PpSXTzhEsJ7"
     

[taxonomies]
  tag = "tags"
  categorie = "categories"